import csv

with open('mascot_list.csv', 'w', newline='') as f:
    thewriter = csv.writer(f)

    # thewriter.writerow(['School', 'Mascot'])
    # thewriter.writerow(['Gonzaga', 'Bulldogs'])
    # thewriter.writerow(['Duke', 'Blue Devils'])
    # thewriter.writerow(['Virginia', 'Cavaliers'])
    # thewriter.writerow(['Kentucky', 'Wildcats'])
    # thewriter.writerow(['Tennessee', 'Volunteers'])
    # thewriter.writerow(['North Carolina', 'Tar Heels'])
    # thewriter.writerow(['Michian State', 'Spartans'])
    # thewriter.writerow(['Michigan', 'Wolverines'])
    # thewriter.writerow(['Houston', 'Cougars'])
    # thewriter.writerow(['Purdue', 'Boilermaker'])
    # thewriter.writerow(['Marquette', 'Golden Eagles'])
    # thewriter.writerow(['Kansas', 'Jayhawks'])
    # thewriter.writerow(['LSU', 'Tigers'])
    # thewriter.writerow(['Maryland', 'Terrapins'])
    # thewriter.writerow(['Texas Tech', 'Red Raiders'])
    # thewriter.writerow(['Nevada', 'Wolf Pack'])
    # thewriter.writerow(['Kansas State', 'Wildcats'])
    # thewriter.writerow(['Iowa State', 'Cyclones'])
    # thewriter.writerow(['Florida State', 'Seminoles'])
    # thewriter.writerow(['Wisconsin', 'Badgers'])
    # thewriter.writerow(['Virginia Tech', 'Hokies'])
    # thewriter.writerow(['Iowa', 'Hawkeyes'])
    # thewriter.writerow(['Cincinnati', 'Bearcats'])
    # thewriter.writerow(['Buffalo', 'Bulls'])
    # thewriter.writerow(['Washington', 'Huskies'])
    # thewriter.writerow(['Baylor', 'Bears'])
    # thewriter.writerow(['Villanova', 'Wildcats'])
    # thewriter.writerow(['Syracuse', 'Orange'])
    # thewriter.writerow(['Mississippi State', 'Bulldogs'])
    # thewriter.writerow(['Louisville', 'Cardinals'])
    # thewriter.writerow(["St. John's", 'Red Storm'])
    # thewriter.writerow(['Ole Miss', 'Rebels'])
    # thewriter.writerow(['Oklahoma', 'Sooners'])
    # thewriter.writerow(['NC State', 'Wolfpack'])
    # thewriter.writerow(['VCU', 'Rams'])
    # thewriter.writerow(['Temple', 'Owls'])
    # thewriter.writerow(['UCF', 'Knights'])
    # thewriter.writerow(['TCU', 'Horned Frogs'])
    # thewriter.writerow(['Wofford', 'Terriers'])
    # thewriter.writerow(['Texas', 'Longhorns'])
    # thewriter.writerow(['Florida', 'Gators'])
    # thewriter.writerow(['Arizona State', 'Sun Devils'])
    # thewriter.writerow(['Seton Hall', 'Pirates'])
    # thewriter.writerow(['Minnesota', 'Golden Gophers'])
    # thewriter.writerow(['Ohio State', 'Buckeyes'])
    # thewriter.writerow(['Alabama', 'Crimson Tide'])
    # thewriter.writerow(['Auburn', 'Tigers'])
    # thewriter.writerow(['Clemson', 'Tigers'])
    # thewriter.writerow(['Belmont', 'Bruins'])
    # thewriter.writerow(['New Mexico State', 'Aggies'])
    # thewriter.writerow(['Lipscomb', 'Bisons'])
    # thewriter.writerow(['Hofstra', 'Pride'])
    # thewriter.writerow(['Yale', 'Bulldogs'])
    # thewriter.writerow(['Old Dominion', 'Monarchs'])
    # thewriter.writerow(['Vermont', 'Catamounts'])
    # thewriter.writerow(['UC Irvine', 'Anteaters'])
    # thewriter.writerow(['South Dakota State', 'Jackrabbits'])
    # thewriter.writerow(['Montana', 'Grizzlies'])
    # thewriter.writerow(['Texas State', 'Bobcats'])
    # thewriter.writerow(['Wright State', 'Raiders'])
    # thewriter.writerow(['Loyola-Chicago', 'Ramblers'])
    # thewriter.writerow(['Radford', 'Highlanders'])
    # thewriter.writerow(['Bucknell', 'Bison'])
    # thewriter.writerow(['Sam Houston State', 'Bearkats'])
    # thewriter.writerow(['Prairie View', 'Panthers'])
    # thewriter.writerow(['Norfolk State', 'Spartans'])
    # thewriter.writerow(['St. Francis PA', 'Red Flash'])
    # thewriter.writerow(['Iona', 'Gaels'])