import csv

with open('team_locations.csv', 'w', newline='') as f:
    thewriter = csv.writer(f)

    thewriter.writerow(['School', 'Location'])
    thewriter.writerow(['Gonzaga', 'Spokane, Washington'])
    thewriter.writerow(['Duke', 'Durham, North Carolina'])
    thewriter.writerow(['Virginia', 'Charlottesville, Virginia'])
    thewriter.writerow(['Kentucky', 'Lexington, Kentucky'])
    thewriter.writerow(['Tennessee', 'Knoxville, Tennessee'])
    thewriter.writerow(['North Carolina', 'Chapel Hill, North Carolina'])
    thewriter.writerow(['Michian State', 'East Lansing, Michigan'])
    thewriter.writerow(['Michigan', 'Ann Arbor, Michigan'])
    thewriter.writerow(['Houston', 'Houston, Texas'])
    thewriter.writerow(['Purdue', 'West Lafayette, Indiana'])
    thewriter.writerow(['Marquette', 'Milwaukee, Wisconsin'])
    thewriter.writerow(['Kansas', 'Lawrence, Kansas'])
    thewriter.writerow(['LSU', 'Baton Rouge, Louisiana'])
    thewriter.writerow(['Maryland', 'College Park, Maryland'])
    thewriter.writerow(['Texas Tech', 'Lubbock, Texas'])
    thewriter.writerow(['Nevada', 'Reno, Nevada'])
    thewriter.writerow(['Kansas State', 'Manhattan, Kansas'])
    thewriter.writerow(['Iowa State', 'Ames, Iowa'])
    thewriter.writerow(['Florida State', 'Tallahassee, Florida'])
    thewriter.writerow(['Wisconsin', 'Madison, Wisconsin'])
    thewriter.writerow(['Virginia Tech', 'Blacksburg, Virginia'])
    thewriter.writerow(['Iowa', 'Iowa City, Iowa'])
    thewriter.writerow(['Cincinnati', 'Cincinnati, Ohio'])
    thewriter.writerow(['Buffalo', 'Buffalo, New York'])
    thewriter.writerow(['Washington', 'Seattle, Washington'])
    thewriter.writerow(['Baylor', 'Waco, Texas'])
    thewriter.writerow(['Villanova', 'Villanova, Pennsylvania'])
    thewriter.writerow(['Syracuse', 'Syracuse, New York'])
    thewriter.writerow(['Mississippi State', 'Starkville, Mississippi'])
    thewriter.writerow(['Louisville', 'Louisville, Kentucky'])
    thewriter.writerow(["St. John's", 'New York City, New York'])
    thewriter.writerow(['Ole Miss', 'Oxford, Mississippi'])
    thewriter.writerow(['Oklahoma', 'Norman, Oklahoma'])
    thewriter.writerow(['NC State', 'Raleigh, North Carolina'])
    thewriter.writerow(['VCU', 'Richmond, Virginia'])
    thewriter.writerow(['Temple', 'Philadelphia, Pennsylvania'])
    thewriter.writerow(['UCF', 'Orlando, Florida'])
    thewriter.writerow(['TCU', 'Fort Worth, Texas'])
    thewriter.writerow(['Wofford', 'Spartanburg, South Carolina'])
    thewriter.writerow(['Texas', 'Austin, Texas'])
    thewriter.writerow(['Florida', 'Gainesville, Florida'])
    thewriter.writerow(['Arizona State', 'Tempe, Arizona'])
    thewriter.writerow(['Seton Hall', 'Newark, New Jerseyy'])
    thewriter.writerow(['Minnesota', 'Minneapolis, Minnesota'])
    thewriter.writerow(['Ohio State', 'Columbus, Ohio'])
    thewriter.writerow(['Alabama', 'Tuscaloosa, Alabama'])
    thewriter.writerow(['Auburn', 'Auburn, Alabama'])
    thewriter.writerow(['Clemson', 'Clemson, South Carolina'])
    thewriter.writerow(['Belmont', 'Nashville, Tennessee'])
    thewriter.writerow(['New Mexico State', 'Las Cruces, New Mexico'])
    thewriter.writerow(['Lipscomb', 'Nashville, Tennessee'])
    thewriter.writerow(['Hofstra', 'Hempstead, New York'])
    thewriter.writerow(['Yale', 'New Haven, Connecticut'])
    thewriter.writerow(['Old Dominion', 'Norfolk, Virginia'])
    thewriter.writerow(['Vermont', 'Burlington, Vermont'])
    thewriter.writerow(['UC Irvine', 'Irvine, California'])
    thewriter.writerow(['South Dakota State', 'Brookings, South Dakota'])
    thewriter.writerow(['Montana', 'Missoula, Montana'])
    thewriter.writerow(['Texas State', 'San Marcos, Texas'])
    thewriter.writerow(['Wright State', 'Fairborn, Ohio'])
    thewriter.writerow(['Loyola-Chicago', 'Chicago, Illinois'])
    thewriter.writerow(['Radford', 'Radford, Virginia'])
    thewriter.writerow(['Bucknell', 'Lewisburg, Pennsylvania'])
    thewriter.writerow(['Sam Houston State', 'Huntsville, Texas'])
    thewriter.writerow(['Prairie View', 'Prairie View, Texas'])
    thewriter.writerow(['Norfolk State', 'Norfolk, Virginia'])
    thewriter.writerow(['St. Francis PA', 'Loretta, Pennslyvania'])
    thewriter.writerow(['Iona', 'New Rochelle, NY'])