import csv

with open('team_colors.csv', 'w', newline='') as f:
    thewriter = csv.writer(f)

    thewriter.writerow(['School', 'Mascot'])
    # thewriter.writerow(['Gonzaga', 'Blue', 'Red'])
    # thewriter.writerow(['Duke', 'Blue', 'Dark Blue'])
    # thewriter.writerow(['Virginia', 'Blue', 'Orange'])
    # thewriter.writerow(['Kentucky', 'Blue', 'White'])
    # thewriter.writerow(['Tennessee', 'Orange', 'White'])
    # thewriter.writerow(['North Carolina', 'Light Blue', 'White'])
    # thewriter.writerow(['Michian State', 'Green', 'White'])
    # thewriter.writerow(['Michigan', 'Yellow', 'Blue'])
    # thewriter.writerow(['Houston', 'Red', 'Dark Red'])
    # thewriter.writerow(['Purdue', 'Black', 'Gold'])
    # thewriter.writerow(['Marquette', 'Blue', 'Yellow'])
    # thewriter.writerow(['Kansas', 'Blue', 'Red'])
    # thewriter.writerow(['LSU', 'Purple', 'Gold'])
    # thewriter.writerow(['Maryland', 'Red', 'Gold'])
    # thewriter.writerow(['Texas Tech', 'Red', 'Black'])
    # thewriter.writerow(['Nevada', 'Blue', 'Grey'])
    # thewriter.writerow(['Kansas State', 'Purple', 'Grey'])
    # thewriter.writerow(['Iowa State', 'Red', 'Gold'])
    # thewriter.writerow(['Florida State', 'Red', 'Gold'])
    # thewriter.writerow(['Wisconsin', 'Red', 'Dark Red'])
    # thewriter.writerow(['Virginia Tech', 'Red', 'Orange'])
    # thewriter.writerow(['Iowa', 'Black', 'Gold'])
    # thewriter.writerow(['Cincinnati', 'Red', 'Black'])
    # thewriter.writerow(['Buffalo', 'Blue', 'White'])
    # thewriter.writerow(['Washington', 'Purple', 'Gold'])
    # thewriter.writerow(['Baylor', 'Green', 'Gold'])
    # thewriter.writerow(['Villanova', 'Blue', 'Light Blue'])
    # thewriter.writerow(['Syracuse', 'Orange', 'Grey'])
    # thewriter.writerow(['Mississippi State', 'Red', 'White'])
    # thewriter.writerow(['Louisville', 'Black', 'Red'])
    # thewriter.writerow(["St. John's", 'Red', 'Blue'])
    # thewriter.writerow(['Ole Miss', 'Red', 'Blue'])
    # thewriter.writerow(['Oklahoma', 'Red', 'Cream'])
    # thewriter.writerow(['NC State', 'Red', 'Black'])
    # thewriter.writerow(['VCU', 'Black', 'Gold'])
    # thewriter.writerow(['Temple', 'Red', 'Yellow'])
    # thewriter.writerow(['UCF', 'Black', 'Gold'])
    # thewriter.writerow(['TCU', 'Purple', 'White'])
    # thewriter.writerow(['Wofford', 'Black', 'Gold'])
    # thewriter.writerow(['Texas', 'Orange', 'Grey'])
    # thewriter.writerow(['Florida', 'Blue', 'Orange'])
    # thewriter.writerow(['Arizona State', 'Red', 'Gold'])
    # thewriter.writerow(['Seton Hall', 'Blue', 'Grey'])
    # thewriter.writerow(['Minnesota', 'Red', 'Yellow'])
    # thewriter.writerow(['Ohio State', 'Red', 'Grey'])
    # thewriter.writerow(['Alabama', 'Red', 'Grey'])
    # thewriter.writerow(['Auburn', 'Blue', 'Orange'])
    # thewriter.writerow(['Clemson', 'Orange', 'Purple'])
    # thewriter.writerow(['Belmont', 'Blue', 'Red'])
    # thewriter.writerow(['New Mexico State', 'Red', 'White'])
    # thewriter.writerow(['Lipscomb', 'Purple', 'Gold'])
    # thewriter.writerow(['Hofstra', 'Blue', 'Gold'])
    # thewriter.writerow(['Yale', 'Blue', 'White'])
    # thewriter.writerow(['Old Dominion', 'Blue', 'Grey'])
    # thewriter.writerow(['Vermont', 'Green', 'Gold'])
    # thewriter.writerow(['UC Irvine', 'Blue', 'Gold'])
    # thewriter.writerow(['South Dakota State', 'Blue', 'Yellow'])
    # thewriter.writerow(['Montana', 'Red', 'Grey'])
    # thewriter.writerow(['Texas State', 'Red', 'Gold'])
    # thewriter.writerow(['Wright State', 'Green', 'Gold'])
    # thewriter.writerow(['Loyola-Chicago', 'Red', 'Gold'])
    # thewriter.writerow(['Radford', 'Red', 'White'])
    # thewriter.writerow(['Bucknell', 'Blue', 'Orange'])
    # thewriter.writerow(['Sam Houston State', 'Orange', 'White'])
    # thewriter.writerow(['Prairie View', 'Purple', 'Gold'])
    # thewriter.writerow(['Norfolk State', 'Green', 'Gold'])
    # thewriter.writerow(['St. Francis PA', 'Red', 'White'])
    # thewriter.writerow(['Iona', 'Red', 'Gold'])