import csv

with open('mascot_list.csv', 'w') as mascot_file:
    fieldnames = {'School', 'Mascot', 'Mascot Rank'}

    csv_writer = csv.DictWriter(mascot_file, fieldnames=fieldnames)
    csv_writer.writeheader()

    csv_writer.writerow({'School': 'Gonzaga', 'Mascot': 'Bulldogs', 'Mascot Rank': ''})
    csv_writer.writerow({'School': 'Duke', 'Mascot': 'Blue Devils'})
    csv_writer.writerow({'School': 'Virginia', 'Mascot': 'Cavaliers'})
    csv_writer.writerow({'School': 'Kentucky', 'Mascot': 'Wildcats'})
    csv_writer.writerow({'School': 'Tennessee', 'Mascot': 'Volunteers'})
    csv_writer.writerow({'School': 'North Carolina', 'Mascot': 'Tar Heels'})
    csv_writer.writerow({'School': 'Michian State', 'Mascot': 'Spartans'})
    csv_writer.writerow({'School': 'Michigan', 'Mascot': 'Wolverines'})
    csv_writer.writerow({'School': 'Houston', 'Mascot': 'Cougars'})
    csv_writer.writerow({'School': 'Purdue', 'Mascot': 'Boilermaker'})
    csv_writer.writerow({'School': 'Marquette', 'Mascot': 'Golden Eagles'})
    csv_writer.writerow({'School': 'Kansas', 'Mascot': 'Jayhawks'})
    csv_writer.writerow({'School': 'LSU', 'Mascot': 'Tigers'})
    csv_writer.writerow({'School': 'Maryland', 'Mascot': 'Terrapins'})
    csv_writer.writerow({'School': 'Texas Tech', 'Mascot': 'Red Raiders'})
    csv_writer.writerow({'School': 'Nevada', 'Mascot': 'Wolf Pack'})
    csv_writer.writerow({'School': 'Kansas State', 'Mascot': 'Wildcats'})
    csv_writer.writerow({'School': 'Iowa State', 'Mascot': 'Cyclones'})
    csv_writer.writerow({'School': 'Florida State', 'Mascot': 'Seminoles'})
    csv_writer.writerow({'School': 'Wisconsin', 'Mascot': 'Badgers'})
    csv_writer.writerow({'School': 'Virginia Tech', 'Mascot': 'Hokies'})
    csv_writer.writerow({'School': 'Iowa', 'Mascot': 'Hawkeyes'})
    csv_writer.writerow({'School': 'Cincinnati', 'Mascot': 'Bearcats'})
    csv_writer.writerow({'School': 'Buffalo', 'Mascot': 'Bulls'})
    csv_writer.writerow({'School': 'Washington', 'Mascot': 'Huskies'})
    csv_writer.writerow({'School': 'Baylor', 'Mascot': 'Bears'})
    csv_writer.writerow({'School': 'Villanova', 'Mascot': 'Wildcats'})
    csv_writer.writerow({'School': 'Syracuse', 'Mascot': 'Orange'})
    csv_writer.writerow({'School': 'Mississippi State', 'Mascot': 'Bulldogs'})
    csv_writer.writerow({'School': 'Louisville', 'Mascot': 'Cardinals'})
    csv_writer.writerow({'School': "St. John's", 'Mascot': 'Red Storm'})
    csv_writer.writerow({'School': 'Ole Miss', 'Mascot': 'Rebels'})
    csv_writer.writerow({'School': 'Oklahoma', 'Mascot': 'Sooners'})
    csv_writer.writerow({'School': 'NC State', 'Mascot': 'Wolfpack'})
    csv_writer.writerow({'School': 'VCU', 'Mascot': 'Rams'})
    csv_writer.writerow({'School': 'Temple', 'Mascot': 'Owls'})
    csv_writer.writerow({'School': 'UCF', 'Mascot': 'Knights'})
    csv_writer.writerow({'School': 'TCU', 'Mascot': 'Horned Frogs'})
    csv_writer.writerow({'School': 'Wofford', 'Mascot': 'Terriers'})
    csv_writer.writerow({'School': 'Texas', 'Mascot': 'Longhorns'})
    csv_writer.writerow({'School': 'Florida', 'Mascot': 'Gators'})
    csv_writer.writerow({'School': 'Arizona State', 'Mascot': 'Sun Devils'})
    csv_writer.writerow({'School': 'Seton Hall', 'Mascot': 'Pirates'})
    csv_writer.writerow({'School': 'Minnesota', 'Mascot': 'Golden Gophers'})
    csv_writer.writerow({'School': 'Ohio State', 'Mascot': 'Buckeyes'})
    csv_writer.writerow({'School': 'Alabama', 'Mascot': 'Crimson Tide'})
    csv_writer.writerow({'School': 'Auburn', 'Mascot': 'Tigers'})
    csv_writer.writerow({'School': 'Clemson', 'Mascot': 'Tigers'})
    csv_writer.writerow({'School': 'Belmont', 'Mascot': 'Bruins'})
    csv_writer.writerow({'School': 'New Mexico State', 'Mascot': 'Aggies'})
    csv_writer.writerow({'School': 'Lipscomb', 'Mascot': 'Bisons'})
    csv_writer.writerow({'School': 'Hofstra', 'Mascot': 'Pride'})
    csv_writer.writerow({'School': 'Yale', 'Mascot': 'Bulldogs'})
    csv_writer.writerow({'School': 'Old Dominion', 'Mascot': 'Monarchs'})
    csv_writer.writerow({'School': 'Vermont', 'Mascot': 'Catamounts'})
    csv_writer.writerow({'School': 'UC Irvine', 'Mascot': 'Anteaters'})
    csv_writer.writerow({'School': 'South Dakota State', 'Mascot': 'Jackrabbits'})
    csv_writer.writerow({'School': 'Montana', 'Mascot': 'Grizzlies'})
    csv_writer.writerow({'School': 'Texas State', 'Mascot': 'Bobcats'})
    csv_writer.writerow({'School': 'Wright State', 'Mascot': 'Raiders'})
    csv_writer.writerow({'School': 'Loyola-Chicago', 'Mascot': 'Ramblers'})
    csv_writer.writerow({'School': 'Radford', 'Mascot': 'Highlanders'})
    csv_writer.writerow({'School': 'Bucknell', 'Mascot': 'Bison'})
    csv_writer.writerow({'School': 'Sam Houston State', 'Mascot': 'Bearkats'})
    csv_writer.writerow({'School': 'Prairie View', 'Mascot': 'Panthers'})
    csv_writer.writerow({'School': 'Norfolk State', 'Mascot': 'Spartans'})
    csv_writer.writerow({'School': 'St. Francis PA', 'Mascot': 'Red Flash'})
    csv_writer.writerow({'School': 'Iona', 'Mascot': 'Gaels'})